# -*- coding: utf-8 -*-
"""05_evaluacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ancantos99/proyectointegrador_ia_grupo8/blob/main/notebooks/05_evaluacion.ipynb

#ENTRENAMIENTO DEL MODELO Y EVALUACIÓN
"""

# Clonar el repo del dataset en /content/dataset
!git lfs install > /dev/null 2>&1
!git clone https://huggingface.co/datasets/YashJain/UI-Elements-Detection-Dataset /content/dataset > /dev/null 2>&1
print("✅ Git LFS instalado y el dataset clonado en '/content/dataset' de forma silenciosa.")

from google.colab import drive
drive.mount('/content/drive')

#Instarlar librerias
!pip install ultralytics > /dev/null 2>&1
print("✅ Ultralytics instalado de forma silenciosa")

#Descargo librerias propias
import os
os.makedirs("/content/tools", exist_ok=True)
!wget -q https://raw.githubusercontent.com/ancantos99/proyectointegrador_ia_grupo8/refs/heads/main/src/tools/YOLODatasetManager.py -O /content/tools/YOLODatasetManager.py > /dev/null 2>&1
!wget -q https://raw.githubusercontent.com/ancantos99/proyectointegrador_ia_grupo8/refs/heads/main/src/tools/YOLOMetricasVisualizar.py -O /content/tools/YOLOMetricasVisualizar.py > /dev/null 2>&1
!wget https://raw.githubusercontent.com/ancantos99/proyectointegrador_ia_grupo8/refs/heads/main/src/data_processing.py -O /content/tools/data_processing.py > /dev/null 2>&1
import importlib
import logging
import sys
sys.path.append("/content/tools")
import YOLODatasetManager
import YOLOMetricasVisualizar
import data_processing
#Recarga de archivos - Para actualizar al último Push
importlib.reload(YOLODatasetManager)
importlib.reload(YOLOMetricasVisualizar)
importlib.reload(data_processing)
from YOLODatasetManager import YOLODatasetManager
from YOLOMetricasVisualizar import YOLOMetricasVisualizar
from data_processing import Data_processing
# Configuración global del Login
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', force=True )

datasetmanager = YOLODatasetManager("/content/dataset")
datasetmanager.yaml_cambiar_carpeta(split="train",nuevaruta="train")
counts = datasetmanager.compute_class_distribution("train")
print("Distribución:", counts)
##datasetmanager.plot_distribution()

"""# APLICAR SOBREMUESTREO"""

processor = Data_processing(datasetmanager.ruta_raiz_dataset)
antes = processor.count_class_distribution("Antes")
processor.oversample_rare_classes();

despues = processor.count_class_distribution("Despues")

"""## 3️⃣ **Entrenamiento del modelo**

"""

from ultralytics import YOLO
datasetmanager.yaml_cambiar_carpeta(split="train",nuevaruta="train")
#Entrenar YOLO de manera clásica con el dataset train, para eso modifico la ruta en el dataset.yaml
model = YOLO("yolov8l.pt")  # yolov8l.pt.
# Cargar dataset usando YOLOv8 Dataset
carpeta_salida = "exp_5" #carpeta donde se van a guardar los resultados del entrenamiento de YOLO y el modelo
model.train(data=datasetmanager.ruta_yaml,
    epochs=100,         #epocas 100
    imgsz= (1920,1080), #tamaño a los que se redimensionara la imagen de entrada #(1920,1080) - 640
    batch=6,            #tamaño del batch (ajustarlo según Vram)
    optimizer="AdamW", #AdamW
    #momentum =0.72765,      # será ignorado si usa Adam/AdamW
    weight_decay = 0.00808107114573286,
    lr0= 0.00004694921598565255,
    lrf= 0.46315,
    name= carpeta_salida,   # nombre del run
    exist_ok=False,         # sobrescribe si ya existe
    project="/content/drive/MyDrive/MIA/Entrenamientos", #En Drive
    patience=15
)

"""## 4️⃣ **Generación de todas las curvas y Evaluación**"""

# Crear objeto Visualizador
carpeta_salida = "exp_5"
visualizer = YOLOMetricasVisualizar(f"/content/drive/MyDrive/MIA/Entrenamientos/{carpeta_salida}/results.csv",
                                    f"/content/drive/MyDrive/MIA/Entrenamientos/{carpeta_salida}/weights/best.pt",datasetmanager.ruta_yaml)

visualizer.plot_loss() # Graficar Loss
visualizer.gap_entretrainyval() # Graficar Gap
visualizer.plot_map()  # Graficar mAP
visualizer.plot_precision_recall_f1() # Graficar Precision, Recall, F1
visualizer.print_final_metrics() # Mostrar métricas finales
#Metricas por Clase
df = visualizer.metrics_por_clase_tabla()   # Imprime Precision, Recall, F1 y mAP50 por clase
display(df)

from ultralytics import YOLO
import cv2
from PIL import Image
from matplotlib import pyplot as plt

ruta_modelo = "/content/drive/MyDrive/MIA/Entrenamientos/exp_5/weights/best.pt"
ruta_imagen = "/content/drive/MyDrive/MIA/webs_prueba/web_senescyt.png";

model = YOLO(ruta_modelo)
results = model.predict(ruta_imagen,conf=0.35)
res = results[0] if isinstance(results, list) else results
res.show()

ruta_modelo = "/content/drive/MyDrive/MIA/Entrenamientos/exp_4_1/weights/best.pt"
ruta_imagen = "/content/drive/MyDrive/MIA/webs_prueba/web_senescyt.png";

model = YOLO(ruta_modelo)
results = model.predict(ruta_imagen,conf=0.35)
res = results[0] if isinstance(results, list) else results
res.show()